name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache npm packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache npm packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/coverage-final.json
        flags: webapp
        name: webapp-coverage
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: true

  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Genesis cleanup
      run: |
        echo "Checking for Genesis artifacts..."

        # Check if genesis/ directory exists (should be deleted)
        if [ -d "genesis" ]; then
          echo "❌ ERROR: genesis/ directory was not deleted!"
          echo "The genesis/ directory should be removed after project setup."
          echo "Run: rm -rf genesis/ && git add . && git commit -m 'Remove genesis'"
          exit 1
        fi
        echo "✅ genesis/ directory properly removed"

        # Check for unreplaced template variables
        if grep -r "{{" . --include="*.md" --include="*.js" --include="*.json" --include="*.html" --include="*.yml" --exclude-dir=node_modules --exclude-dir=.git 2>/dev/null; then
          echo "❌ ERROR: Found unreplaced template variables ({{...}})"
          echo "All {{VARIABLE}} placeholders must be replaced with actual values."
          exit 1
        fi
        echo "✅ No unreplaced template variables"

    - name: Quality gate passed
      run: |
        echo "✅ All quality checks passed!"
        echo "✅ Linting: PASSED"
        echo "✅ Tests: PASSED"
        echo "✅ Coverage: PASSED"
        echo "✅ Genesis cleanup: PASSED"

