name: Deploy Web App to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to {{DEPLOY_FOLDER}}/ directory
        run: |
          # Copy web app files to {{DEPLOY_FOLDER}}/ for GitHub Pages
          cp -f index.html {{DEPLOY_FOLDER}}/
          cp -rf js/* {{DEPLOY_FOLDER}}/js/
          cp -rf css/* {{DEPLOY_FOLDER}}/css/

          echo "✅ Files copied to {{DEPLOY_FOLDER}}/ directory"

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add {{DEPLOY_FOLDER}}/
          git commit -m "docs: Deploy web app to GitHub Pages [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Deployment summary
        run: |
          echo "✅ Web app deployed successfully!"
          echo "🌐 GitHub Pages will update in 2-5 minutes"
          echo "🔗 URL: {{GITHUB_PAGES_URL}}"


